export const templateSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    additionalProperties: false,
    required: ['title', 'description', 'topic', 'suggestedTags', 'questions'],
    properties: {
        title: { type: 'string' },
        description: { type: 'string' },
        topic: { type: 'string' },
        suggestedTags: {
            type: 'array',
            items: { type: 'string' },
        },
        questions: {
            type: 'array',
            items: {
                $ref: '#/definitions/GeneratedQuestion',
            },
        },
    },
    definitions: {
        GeneratedQuestion: {
            type: 'object',
            additionalProperties: false,
            required: ['order', 'showInResults', 'isRequired', 'data'],
            properties: {
                order: { type: 'number' },
                showInResults: { type: 'boolean' },
                isRequired: { type: 'boolean' },
                data: { $ref: '#/definitions/AnyQuestionDetails' },
            },
        },
        AnyQuestionDetails: {
            anyOf: [
                { $ref: '#/definitions/ShortTextDetails' },
                { $ref: '#/definitions/LongTextDetails' },
                { $ref: '#/definitions/SingleChoiceDetails' },
                { $ref: '#/definitions/MultipleChoiceDetails' },
                { $ref: '#/definitions/DropdownDetails' },
                { $ref: '#/definitions/ScaleDetails' },
                { $ref: '#/definitions/RatingDetails' },
                { $ref: '#/definitions/DateDetails' },
                { $ref: '#/definitions/TimeDetails' },
            ],
        },
        QuestionType: {
            type: 'number',
            enum: [1, 2, 3, 4, 5, 6, 7, 8, 9],
        },
        ShortTextDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'maxLength',
                'placeholder',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                maxLength: { type: 'number' },
                placeholder: { type: 'string' },
            },
        },
        LongTextDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'maxLength',
                'placeholder',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                maxLength: { type: 'number' },
                placeholder: { type: 'string' },
            },
        },
        SingleChoiceDetails: {
            type: 'object',
            additionalProperties: false,
            required: ['type', 'title', 'description', 'options'],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                options: {
                    type: 'array',
                    items: { type: 'string' },
                },
            },
        },
        MultipleChoiceDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'options',
                'maxSelections',
                'minSelections',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                options: {
                    type: 'array',
                    items: { type: 'string' },
                },
                maxSelections: { type: 'number' },
                minSelections: { type: 'number' },
            },
        },
        DropdownDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'options',
                'defaultOption',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                options: {
                    type: 'array',
                    items: { type: 'string' },
                },
                defaultOption: { type: 'string' },
            },
        },
        ScaleDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'minValue',
                'maxValue',
                'minLabel',
                'maxLabel',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                minValue: { type: 'number' },
                maxValue: { type: 'number' },
                minLabel: { type: 'string' },
                maxLabel: { type: 'string' },
            },
        },
        RatingDetails: {
            type: 'object',
            additionalProperties: false,
            required: [
                'type',
                'title',
                'description',
                'maxRating',
                'ratingLabel',
            ],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                maxRating: { type: 'number' },
                ratingLabel: { type: 'string' },
            },
        },
        DateDetails: {
            type: 'object',
            additionalProperties: false,
            required: ['type', 'title', 'description', 'startDate', 'pastDate'],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                startDate: { type: 'string' },
                pastDate: { type: 'string' },
            },
        },
        TimeDetails: {
            type: 'object',
            additionalProperties: false,
            required: ['type', 'title', 'description', 'startDate', 'pastDate'],
            properties: {
                type: { $ref: '#/definitions/QuestionType' },
                title: { type: 'string' },
                description: { type: 'string' },
                startDate: { type: 'string' },
                pastDate: { type: 'string' },
            },
        },
    },
};
